`timescale 1ns/1ns

//============================================================
// Immediate generator compliance test
//
// Differential test against an independent model derived from
// the RISC-V spec (Vol I, Fig 2.4 immediate encodings), NOT
// from this project's assembler or RTL.
//
// Vectors are generated by tools/gen_imm_vectors.py and read
// from imm_vec.txt as "instruction expected_imm" pairs.
//============================================================

module tb_imm_compliance;

    localparam MAX_VEC = 1000;

    reg  [31:0] instruction;
    wire [63:0] imm_out;

    reg [31:0] vec_instr [0:MAX_VEC-1];
    reg [63:0] vec_expect[0:MAX_VEC-1];

    integer n_vec;
    integer i;
    integer errors;

    imm_gen dut (
        .instruction (instruction),
        .imm_out     (imm_out)
    );

    // Load "instr expected" pairs. $readmemh on a file with two hex columns
    // per line fills the array in sequence, so read into a flat array and
    // de-interleave.
    reg [63:0] flat [0:2*MAX_VEC-1];

    initial begin
        for (i = 0; i < 2*MAX_VEC; i = i + 1)
            flat[i] = 64'hXXXXXXXX_XXXXXXXX;

        $readmemh("imm_vec.txt", flat);

        // Count how many valid pairs we actually got.
        n_vec = 0;
        for (i = 0; i < MAX_VEC; i = i + 1) begin
            if (flat[2*i] !== 64'hXXXXXXXX_XXXXXXXX) begin
                vec_instr[i]  = flat[2*i][31:0];
                vec_expect[i] = flat[2*i + 1];
                n_vec = n_vec + 1;
            end
        end

        errors = 0;

        $display("================================================");
        $display("IMMEDIATE GENERATOR COMPLIANCE TEST");
        $display("================================================");
        $display("Vectors from an independent spec-derived model.");
        $display("Loaded %0d vectors.", n_vec);
        $display("------------------------------------------------");

        for (i = 0; i < n_vec; i = i + 1) begin
            instruction = vec_instr[i];
            #1;

            if (imm_out !== vec_expect[i]) begin
                errors = errors + 1;
                if (errors <= 10)
                    $display("FAIL instr=0x%08h opcode=%07b  rtl=0x%016h  spec=0x%016h",
                             instruction, instruction[6:0], imm_out, vec_expect[i]);
            end
        end

        $display("------------------------------------------------");
        $display("CHECKS: %0d   ERRORS: %0d", n_vec, errors);
        if (errors == 0)
            $display("RESULT: IMM GEN MATCHES RISC-V SPEC");
        else
            $display("RESULT: IMM GEN DEVIATES FROM SPEC");
        $display("================================================");
        $finish;
    end

endmodule
